In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/IBM_credit_card_transaction.csv')

In [3]:
df.head(3)

User  Card  Year  Month  Day   Time   Amount           Use Chip  \
0     0     0  2002      9    1  06:21  $134.09  Swipe Transaction   
1     0     0  2002      9    1  06:42   $38.48  Swipe Transaction   
2     0     0  2002      9    2  06:22  $120.34  Swipe Transaction   

         Merchant Name  Merchant City Merchant State      Zip   MCC Errors?  \
0  3527213246127876953       La Verne             CA  91750.0  5300     NaN   
1  -727612092139916043  Monterey Park             CA  91754.0  5411     NaN   
2  -727612092139916043  Monterey Park             CA  91754.0  5411     NaN   

  Is Fraud?  
0        No  
1        No  
2        No

In [4]:
df.shape

(24386900, 15)

In [5]:
df.dtypes

User                int64
Card                int64
Year                int64
Month               int64
Day                 int64
Time               object
Amount             object
Use Chip           object
Merchant Name       int64
Merchant City      object
Merchant State     object
Zip               float64
MCC                 int64
Errors?            object
Is Fraud?          object
dtype: object

In [6]:
df['User'].nunique()

2000

In [7]:
df['User'].unique()

array([   0,    1,    2, ..., 1997, 1998, 1999], shape=(2000,))

In [8]:
df['Card'].unique()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
df.isna().sum()

User                     0
Card                     0
Year                     0
Month                    0
Day                      0
Time                     0
Amount                   0
Use Chip                 0
Merchant Name            0
Merchant City            0
Merchant State     2720821
Zip                2878135
MCC                      0
Errors?           23998469
Is Fraud?                0
dtype: int64

In [10]:
df['Errors?'].value_counts()

Errors?
Insufficient Balance,                                   242783
Bad PIN,                                                 58918
Technical Glitch,                                        48157
Bad Card Number,                                         13321
Bad CVV,                                                 10740
Bad Expiration,                                          10716
Bad Zipcode,                                              2079
Bad PIN,Insufficient Balance,                              581
Insufficient Balance,Technical Glitch,                     457
Bad PIN,Technical Glitch,                                  128
Bad Card Number,Insufficient Balance,                      122
Bad CVV,Insufficient Balance,                               89
Bad Expiration,Insufficient Balance,                        78
Bad Card Number,Bad CVV,                                    60
Bad Card Number,Bad Expiration,                             54
Bad Expiration,Bad CVV,                        

In [11]:
df['Is Fraud?'].value_counts()

Is Fraud?
No     24357143
Yes       29757
Name: count, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 15 columns):
 #   Column          Dtype  
---  ------          -----  
 0   User            int64  
 1   Card            int64  
 2   Year            int64  
 3   Month           int64  
 4   Day             int64  
 5   Time            object 
 6   Amount          object 
 7   Use Chip        object 
 8   Merchant Name   int64  
 9   Merchant City   object 
 10  Merchant State  object 
 11  Zip             float64
 12  MCC             int64  
 13  Errors?         object 
 14  Is Fraud?       object 
dtypes: float64(1), int64(7), object(7)
memory usage: 2.7+ GB


In [13]:
df["card_id"] = df["User"].astype(str) + "_" + df["Card"].astype(str)

In [14]:
df.Amount.head(5)

0    $134.09
1     $38.48
2    $120.34
3    $128.95
4    $104.71
Name: Amount, dtype: object

In [15]:
df["Amount"]=df["Amount"].str.replace("$","")

In [16]:
df["Amount"]=df["Amount"].astype(float)
df["Amount"].head(5)

0    134.09
1     38.48
2    120.34
3    128.95
4    104.71
Name: Amount, dtype: float64

In [17]:
df.head(3)

User  Card  Year  Month  Day   Time  Amount           Use Chip  \
0     0     0  2002      9    1  06:21  134.09  Swipe Transaction   
1     0     0  2002      9    1  06:42   38.48  Swipe Transaction   
2     0     0  2002      9    2  06:22  120.34  Swipe Transaction   

         Merchant Name  Merchant City Merchant State      Zip   MCC Errors?  \
0  3527213246127876953       La Verne             CA  91750.0  5300     NaN   
1  -727612092139916043  Monterey Park             CA  91754.0  5411     NaN   
2  -727612092139916043  Monterey Park             CA  91754.0  5411     NaN   

  Is Fraud? card_id  
0        No     0_0  
1        No     0_0  
2        No     0_0

In [18]:
df["Hour"] = df["Time"].str [0:2]
df["Minute"] = df["Time"].str [3:5]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 18 columns):
 #   Column          Dtype  
---  ------          -----  
 0   User            int64  
 1   Card            int64  
 2   Year            int64  
 3   Month           int64  
 4   Day             int64  
 5   Time            object 
 6   Amount          float64
 7   Use Chip        object 
 8   Merchant Name   int64  
 9   Merchant City   object 
 10  Merchant State  object 
 11  Zip             float64
 12  MCC             int64  
 13  Errors?         object 
 14  Is Fraud?       object 
 15  card_id         object 
 16  Hour            object 
 17  Minute          object 
dtypes: float64(2), int64(7), object(9)
memory usage: 3.3+ GB


In [20]:
df.Hour.head(5)

0    06
1    06
2    06
3    17
4    06
Name: Hour, dtype: object

In [21]:
df = df.drop(["Time","User","Card"],axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 15 columns):
 #   Column          Dtype  
---  ------          -----  
 0   Year            int64  
 1   Month           int64  
 2   Day             int64  
 3   Amount          float64
 4   Use Chip        object 
 5   Merchant Name   int64  
 6   Merchant City   object 
 7   Merchant State  object 
 8   Zip             float64
 9   MCC             int64  
 10  Errors?         object 
 11  Is Fraud?       object 
 12  card_id         object 
 13  Hour            object 
 14  Minute          object 
dtypes: float64(2), int64(5), object(8)
memory usage: 2.7+ GB


In [22]:
df["Errors?"].unique()

array([nan, 'Technical Glitch,', 'Insufficient Balance,', 'Bad PIN,',
       'Bad PIN,Insufficient Balance,', 'Bad Expiration,',
       'Bad PIN,Technical Glitch,', 'Bad Card Number,', 'Bad CVV,',
       'Bad Zipcode,', 'Insufficient Balance,Technical Glitch,',
       'Bad Card Number,Insufficient Balance,',
       'Bad Card Number,Bad CVV,', 'Bad CVV,Insufficient Balance,',
       'Bad Card Number,Bad Expiration,', 'Bad Expiration,Bad CVV,',
       'Bad Expiration,Insufficient Balance,',
       'Bad Expiration,Technical Glitch,',
       'Bad Card Number,Bad Expiration,Technical Glitch,',
       'Bad CVV,Technical Glitch,', 'Bad Card Number,Technical Glitch,',
       'Bad Zipcode,Insufficient Balance,',
       'Bad Zipcode,Technical Glitch,',
       'Bad Card Number,Bad Expiration,Insufficient Balance,'],
      dtype=object)

In [23]:
df["Errors?"]= df["Errors?"].fillna("No error")

In [24]:
#The two columns Zip and Merchant state contains missing values which can affect our graph. Moreover these information can be extracted from the column Merchant City so we will drop them.
df = df.drop(["Zip","Merchant State"],axis=1)

In [25]:
# change the is fraud column to binary 
df["Is Fraud?"] = df["Is Fraud?"].apply(lambda x: 1 if x == 'Yes' else 0)

In [26]:

from sklearn.preprocessing import LabelEncoder

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 13 columns):
 #   Column         Dtype  
---  ------         -----  
 0   Year           int64  
 1   Month          int64  
 2   Day            int64  
 3   Amount         float64
 4   Use Chip       object 
 5   Merchant Name  int64  
 6   Merchant City  object 
 7   MCC            int64  
 8   Errors?        object 
 9   Is Fraud?      int64  
 10  card_id        object 
 11  Hour           object 
 12  Minute         object 
dtypes: float64(1), int64(6), object(6)
memory usage: 2.4+ GB


In [28]:
df["Merchant City"]=LabelEncoder().fit_transform(df["Merchant City"])
df["Use Chip"]=LabelEncoder().fit_transform(df["Use Chip"])
df["Errors?"]=LabelEncoder().fit_transform(df["Errors?"])

In [29]:
df["Errors?"].unique()

array([22, 23, 20, 14, 15, 10, 16,  3,  0, 17, 21,  8,  4,  1,  5, 11, 12,
       13,  7,  2,  9, 18, 19,  6])

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24386900 entries, 0 to 24386899
Data columns (total 13 columns):
 #   Column         Dtype  
---  ------         -----  
 0   Year           int64  
 1   Month          int64  
 2   Day            int64  
 3   Amount         float64
 4   Use Chip       int64  
 5   Merchant Name  int64  
 6   Merchant City  int64  
 7   MCC            int64  
 8   Errors?        int64  
 9   Is Fraud?      int64  
 10  card_id        object 
 11  Hour           object 
 12  Minute         object 
dtypes: float64(1), int64(9), object(3)
memory usage: 2.4+ GB
